### ISSUE TITLE
vsprintf error

### ISSUE THREAD

**Issue by Guralol** [CowNowB/Aimstar#10]
I'm a newbie and when I run it with Debug x64 it gives the following error. 
![QQ20240818-131319](https://github.com/user-attachments/assets/928b9bcc-c95a-461c-bff7-ac2ed72ef731) 
I've tried the workaround on the webbut it didn't work

**Comment by MehPropy** [comment]
You have to build it as Ring0 or Ring3, not Debug nor Release. The error is saying that vsprintf is unsafe, so before changing anything in the code, try to build it as Ring3 or Ring0 and see if it will work (it should). If that somehow dosent work, replace all vsprintf instances with vsprintf_s.
Cheers.

**Comment by CowNowB** [comment]
don't build as Debug

**Comment by Guralol** [comment]
> 您必须将其构建为 Ring0 或 Ring3，而不是 Debug 或 Release。错误是说 vsprintf 不安全，因此在更改代码中的任何内容之前，请尝试将其构建为 Ring3 或 Ring0，看看它是否可以工作（它应该）。如果这在某种程度上不起作用，请用 vsprintf_s. Cheers 替换所有 vsprintf 实例。
好,我使用了R0和R3进行构建，虽然已构建成功，但程序不会正常运行,如下图
![QQ20240818-213111](https://github.com/user-attachments/assets/7f818721-cd16-4a3c-9e3c-9c02e103a2c3)
R0和R0都是相同的结果，请问有什么解决办法吗？

**Comment by Guralol** [comment]
> 不要构建为 Debug

Though it build successfully,it can't run normally

**Comment by Guralol** [comment]
> 您必须将其构建为 Ring0 或 Ring3，而不是 Debug 或 Release。错误是说 vsprintf 不安全，因此在更改代码中的任何内容之前，请尝试将其构建为 Ring3 或 Ring0，看看它是否可以工作（它应该）。如果这在某种程度上不起作用，请用 vsprintf_s. Cheers 替换所有 vsprintf 实例。

我现在已经完全的成功了，但必须使用Ctrl+F5运行它，感谢你的帮助
