### ISSUE TITLE
Game crashes when opening aimstar

### ISSUE THREAD

**Issue by xin6x6** [CowNowB/Aimstar#5]
cs2 crashes when i open aimstar.
![image](https://github.com/user-attachments/assets/d7095cea-786f-4db9-8fae-679b0c24c059)

**Comment by Mongkay** [comment]
Same Problem

**Comment by MehPropy** [comment]
Calm down kids, the cs structure changed so it will take a while until its fixed.

**Comment by Ruslan2812** [comment]
Updated the offsets the game still crashes when starting a match

**Comment by MehPropy** [comment]
> Updated the offsets the game still crashes when starting a match

as I said, the game's structure changed which means that every cheat is outdated, wait until it's fixed by devs.
